apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: deis-minio-sync
  namespace: deis
  labels:
    heritage: helm
    release: v2-beta
spec:
  template:
    metadata:
      name:  minio-sync
      labels:
        heritage: helm
    spec:
      containers:
      - name:  minio-sync
        image: quay.io/deisci/minio-sync:v2-beta
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - name: btsync-secret
          mountPath: /var/run/secrets/deis/minio/secret
          readOnly: true
        - name: config
          mountPath: /config
        - name: minio-data
          mountPath: /mnt/minio/data
      volumes:
      - name: btsync-secret
        secret:
          secretName: minio-sync
      - name: config
        hostPath:
          path: /mnt/minio/config
      - name: minio-data
        hostPath:
          path: /mnt/minio/data
